apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fullstack-app
type: Opaque
stringData:
  MONGODB_PASSWORD: "password123"
  REDIS_PASSWORD: "redis123"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "password123"
